// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdlhQOHHwhRGz9SibV1O-QGK9-yT28_qQ',
    appId: '1:116147973494:web:7b7f33d5a84ec020d5de57',
    messagingSenderId: '116147973494',
    projectId: 'ecommerce-app-efdf4',
    authDomain: 'ecommerce-app-efdf4.firebaseapp.com',
    storageBucket: 'ecommerce-app-efdf4.appspot.com',
    // storageBucket: "ecommerce-app-efdf4.firebasestorage.app",
    measurementId: 'G-WZXKVGW946',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCojlvT-EQwB4QhRJxJ4o6zKuVtx5QWm64',
    appId: '1:116147973494:android:d21058a0277bd93ed5de57',
    messagingSenderId: '116147973494',
    projectId: 'ecommerce-app-efdf4',
    storageBucket: 'ecommerce-app-efdf4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_PkDZUqJpUj6S6G-ZlNbgeRfxN__x6os',
    appId: '1:116147973494:ios:c4a80e7531e544fed5de57',
    messagingSenderId: '116147973494',
    projectId: 'ecommerce-app-efdf4',
    storageBucket: 'ecommerce-app-efdf4.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_PkDZUqJpUj6S6G-ZlNbgeRfxN__x6os',
    appId: '1:116147973494:ios:c4a80e7531e544fed5de57',
    messagingSenderId: '116147973494',
    projectId: 'ecommerce-app-efdf4',
    storageBucket: 'ecommerce-app-efdf4.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdlhQOHHwhRGz9SibV1O-QGK9-yT28_qQ',
    appId: '1:116147973494:web:fe7c4e59f546aa77d5de57',
    messagingSenderId: '116147973494',
    projectId: 'ecommerce-app-efdf4',
    authDomain: 'ecommerce-app-efdf4.firebaseapp.com',
    storageBucket: 'ecommerce-app-efdf4.appspot.com',
    measurementId: 'G-ZYWXZY9X4S',
  );
}
